language: python
python:
- 2.7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- mkdir -p buildout-cache/downloads build/html
- python bootstrap.py -c travis.cfg
- bin/buildout -c travis.cfg
before_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- bin/sphinx-build -b html src/plone.themepreview/source build/html
after_script:
- travis-artifacts upload --path build/html
env:
  global:
  - ARTIFACTS_S3_BUCKET=plonetheme.onegov
  - SPHINX_PROJECT=plonetheme.onegov
  - SPHINX_COPYRIGHT=4teamwork
  - ROBOT_CONFIGURE_PACKAGES=plone.app.dexterity,plonetheme.onegov
  - ROBOT_APPLY_PROFILES=plonetheme.onegov:default
  - secure: gXZKMOMp3TBlH8ih22bxz+BTcFl9nzReaN18rydH8JBNiJjJeaKSdxnQ1vt3nlUxyE1v+e2KqhlaV/Qr7Qov5x8ijyg642XIe5p0QPJr2SwBuwZGDYkZN1EFxKFm+rmY2qgIIoSlfPfCe78MjIdjNSxz0Z2IqXfNHHpiMxQnU60=
  - secure: mlpVe02HrXCqyoxRkgiLNk3oaa9NKCQ4rzKdbOnqmdH1dG2ThatXGkI0Ds9q1zkLIE1Tbst7CqucyfZKA8yvy0ZQalYsFk9GvDI1WS1GtWxJBWMo/9gqaIlxKBOSTKQsletlc3DsxhHZJDqVEoLT2OflE0GNvWwxAML9ZPmKNAE=
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - ! 'Sphinx: http://plonetheme-bootstrap.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/'
